<?php
// config/db.php
$host = 'localhost';
$dbName = 'rawfit'; // <-- YOUR DATABASE NAME
$user = 'root';
$pass = ''; // <-- put your MySQL password here
$charset = 'utf8mb4';
$dsn = "mysql:host=$host;charset=$charset";
$options = [
    PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
    PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
    PDO::ATTR_EMULATE_PREPARES => false,
];
try {
    // 1. Connect without selecting a DB
    $pdo = new PDO($dsn, $user, $pass, $options);
    // 2. Create DB if missing
    $pdo->exec("CREATE DATABASE IF NOT EXISTS `$dbName` CHARACTER SET $charset COLLATE utf8mb4_unicode_ci");
    $pdo->exec("USE `$dbName`");
    // 3. Create ALL tables (original + user-workout tables + users)
    $sql = "
    -- Users table (required for user_id)
    CREATE TABLE IF NOT EXISTS users (
        id INT AUTO_INCREMENT PRIMARY KEY,
        username VARCHAR(50) UNIQUE NOT NULL,
        email VARCHAR(100) UNIQUE NOT NULL,
        password_hash VARCHAR(255) NOT NULL,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    ) ENGINE=InnoDB;
    -- Exercises (from wger)
    CREATE TABLE IF NOT EXISTS exercises (
        id INT PRIMARY KEY,
        name VARCHAR(255) NOT NULL,
        bodyPart VARCHAR(100),
        target VARCHAR(100),
        equipment VARCHAR(100),
        gifUrl TEXT,
        instructions TEXT,
        image_url VARCHAR(500),
        INDEX(name)
    ) ENGINE=InnoDB;
    -- Original workout splits
    CREATE TABLE IF NOT EXISTS workout_splits (
        id INT AUTO_INCREMENT PRIMARY KEY,
        name VARCHAR(255) NOT NULL,
        user VARCHAR(50) NOT NULL DEFAULT 'aswa',
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    ) ENGINE=InnoDB;
    CREATE TABLE IF NOT EXISTS split_days (
        id INT AUTO_INCREMENT PRIMARY KEY,
        split_id INT NOT NULL,
        day_name ENUM('Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday') NOT NULL,
        day_number TINYINT NOT NULL,
        FOREIGN KEY (split_id) REFERENCES workout_splits(id) ON DELETE CASCADE
    ) ENGINE=InnoDB;
    CREATE TABLE IF NOT EXISTS split_exercises (
        id INT AUTO_INCREMENT PRIMARY KEY,
        split_day_id INT NOT NULL,
        exercise_id INT NOT NULL,
        sets INT DEFAULT 3,
        reps VARCHAR(20) DEFAULT '8-12',
        rest_seconds INT DEFAULT 60,
        FOREIGN KEY (split_day_id) REFERENCES split_days(id) ON DELETE CASCADE,
        FOREIGN KEY (exercise_id) REFERENCES exercises(id) ON DELETE RESTRICT
    ) ENGINE=InnoDB;
    CREATE TABLE IF NOT EXISTS split_exercises_temp (
        id INT AUTO_INCREMENT PRIMARY KEY,
        user VARCHAR(50) NOT NULL DEFAULT 'aswa',
        day_index TINYINT NOT NULL,
        exercise_id INT NOT NULL,
        exercise_name TEXT NOT NULL,
        target VARCHAR(100),
        bodyPart VARCHAR(100),
        equipment VARCHAR(100),
        gifUrl TEXT,
        sets INT DEFAULT 3,
        reps VARCHAR(20) DEFAULT '8-12',
        rest INT DEFAULT 60,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        INDEX(user, day_index)
    ) ENGINE=InnoDB;
    -- === USER PERSONAL WORKOUT TABLES ===
    CREATE TABLE IF NOT EXISTS user_workouts (
        id INT AUTO_INCREMENT PRIMARY KEY,
        user_id INT NOT NULL,
        split_id INT NOT NULL,
        name VARCHAR(255) NOT NULL,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
        FOREIGN KEY (split_id) REFERENCES workout_splits(id) ON DELETE CASCADE,
        UNIQUE KEY unique_user_split (user_id, split_id)
    ) ENGINE=InnoDB;
    CREATE TABLE IF NOT EXISTS user_workout_days (
        id INT AUTO_INCREMENT PRIMARY KEY,
        user_workout_id INT NOT NULL,
        day_name ENUM('Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday') NOT NULL,
        day_number TINYINT NOT NULL,
        FOREIGN KEY (user_workout_id) REFERENCES user_workouts(id) ON DELETE CASCADE
    ) ENGINE=InnoDB;
    CREATE TABLE IF NOT EXISTS user_workout_exercises (
        id INT AUTO_INCREMENT PRIMARY KEY,
        user_workout_day_id INT NOT NULL,
        exercise_id INT NOT NULL,
        sets INT NOT NULL,
        reps VARCHAR(50),
        rest_seconds INT,
        FOREIGN KEY (user_workout_day_id) REFERENCES user_workout_days(id) ON DELETE CASCADE,
        FOREIGN KEY (exercise_id) REFERENCES exercises(id) ON DELETE RESTRICT
    ) ENGINE=InnoDB;
    ";
    // Execute each statement
    foreach (explode(';', $sql) as $stmt) {
        $stmt = trim($stmt);
        if ($stmt) {
            $pdo->exec($stmt . ';');
        }
    }
    // 4. Seed exercises only if table is empty
    $cnt = $pdo->query("SELECT COUNT(*) FROM exercises")->fetchColumn();
    if ($cnt == 0) {
        $stmt = $pdo->prepare("
            INSERT INTO exercises (id, name, bodyPart, target, equipment, gifUrl, instructions, image_url)
            VALUES (?,?,?,?,?,?,?,?)
        ");
        // === 50 CHEST EXERCISES (IDs 1–50) ===
        $exercises = [
            [1,'Push-up','Chest','Pectorals','Bodyweight','https://i.imgur.com/0Y8p3fG.gif','Lower chest to ground, push back up. Keep core tight.',''],
            [2,'Bench Press (Barbell)','Chest','Pectorals','Barbell','https://i.imgur.com/1q2w3eR.gif','Lie on bench, lower bar to chest, press up explosively.',''],
            [3,'Incline Dumbbell Press','Chest','Upper Chest','Dumbbell','https://i.imgur.com/4t5y6uI.gif','Use 30–45° incline, press dumbbells up.',''],
            [4,'Cable Fly','Chest','Pectorals','Cable','https://i.imgur.com/a1b2c3d.gif','Pull cables from wide to center in front of chest.',''],
            [5,'Dips (Chest)','Chest','Lower Pecs','Bodyweight','https://i.imgur.com/e4f5g6h.gif','Lean forward, lower until shoulders below elbows.',''],
            [6,'Decline Push-up','Chest','Lower Chest','Bodyweight','https://i.imgur.com/i7j8k9l.gif','Feet elevated, perform push-up.',''],
            [7,'Dumbbell Pullover','Chest','Pectorals','Dumbbell','https://i.imgur.com/m0n1o2p.gif','Lie across bench, lower dumbbell behind head, pull up.',''],
            [8,'Plate Press','Chest','Pectorals','Plate','https://i.imgur.com/q3r4s5t.gif','Press plate forward while squeezing chest.',''],
            [9,'Machine Chest Press','Chest','Pectorals','Machine','https://i.imgur.com/u6v7w8x.gif','Push handles forward on machine.',''],
            [10,'Svende Press','Chest','Pectorals','Plate','https://i.imgur.com/y9z0a1b.gif','Hold plate at chest, press out and back.',''],
            [11,'Archer Push-up','Chest','Pectorals','Bodyweight','https://i.imgur.com/c2d3e4f.gif','Shift weight to one arm, lower, push up.',''],
            [12,'Clap Push-up','Chest','Pectorals','Bodyweight','https://i.imgur.com/g5h6i7j.gif','Push explosively, clap hands in air.',''],
            [13,'Diamond Push-up','Chest','Inner Chest','Bodyweight','https://i.imgur.com/k8l9m0n.gif','Hands form diamond under chest.',''],
            [14,'Wide Push-up','Chest','Outer Chest','Bodyweight','https://i.imgur.com/o1p2q3r.gif','Hands wider than shoulders.',''],
            [15,'Pike Push-up','Chest','Upper Chest','Bodyweight','https://i.imgur.com/s4t5u6v.gif','Hips up, head toward floor.',''],
            [16,'Incline Push-up','Chest','Upper Chest','Bodyweight','https://i.imgur.com/w7x8y9z.gif','Hands on bench, perform push-up.',''],
            [17,'Decline Bench Press','Chest','Lower Chest','Barbell','https://i.imgur.com/a0b1c2d.gif','Feet elevated, press bar up.',''],
            [18,'Flat Dumbbell Fly','Chest','Pectorals','Dumbbell','https://i.imgur.com/e3f4g5h.gif','Lie flat, lower dumbbells out to sides.',''],
            [19,'Incline Cable Fly','Chest','Upper Chest','Cable','https://i.imgur.com/i6j7k8l.gif','Pull cables from low to high.',''],
            [20,'Guillotine Press','Chest','Upper Chest','Barbell','https://i.imgur.com/m9n0o1p.gif','Lower bar to neck, press up.',''],
            [21,'Low Cable Crossover','Chest','Lower Pecs','Cable','https://i.imgur.com/q2r3s4t.gif','Pull cables from low to high.',''],
            [22,'High Cable Crossover','Chest','Upper Pecs','Cable','https://i.imgur.com/u5v6w7x.gif','Pull cables from high to low.',''],
            [23,'Single-Arm Cable Fly','Chest','Pectorals','Cable','https://i.imgur.com/y8z9a0b.gif','Unilateral fly with cable.',''],
            [24,'Push-up Plus','Chest','Serratus','Bodyweight','https://i.imgur.com/c1d2e3f.gif','Protract shoulders at top of push-up.',''],
            [25,'Hindu Push-up','Chest','Pectorals','Bodyweight','https://i.imgur.com/g4h5i6j.gif','Dive down, swoop up.',''],
            [26,'Spiderman Push-up','Chest','Pectorals','Bodyweight','https://i.imgur.com/k7l8m9n.gif','Bring knee to elbow on each rep.',''],
            [27,'Typewriter Push-up','Chest','Pectorals','Bodyweight','https://i.imgur.com/o0p1q2r.gif','Slide side to side at bottom.',''],
            [28,'Weighted Push-up','Chest','Pectorals','Plate','https://i.imgur.com/s3t4u5v.gif','Plate on back, perform push-up.',''],
            [29,'Ring Push-up','Chest','Pectorals','Rings','https://i.imgur.com/w6x7y8z.gif','Unstable push-up on rings.',''],
            [30,'Deficit Push-up','Chest','Pectorals','Bodyweight','https://i.imgur.com/a9b0c1d.gif','Hands on blocks, deeper range.',''],
            [31,'Banded Push-up','Chest','Pectorals','Band','https://i.imgur.com/e2f3g4h.gif','Band across back for resistance.',''],
            [32,'Paused Bench Press','Chest','Pectorals','Barbell','https://i.imgur.com/i5j6k7l.gif','Pause 1–2s on chest.',''],
            [33,'Spoto Press','Chest','Pectorals','Barbell','https://i.imgur.com/m8n9o0p.gif','Pause 1" above chest.',''],
            [34,'Reverse-Grip Bench Press','Chest','Upper Chest','Barbell','https://i.imgur.com/q1r2s3t.gif','Underhand grip, press up.',''],
            [35,'Larsen Press','Chest','Pectorals','Barbell','https://i.imgur.com/u4v5w6x.gif','No leg drive, paused.',''],
            [36,'Floor Press','Chest','Pectorals','Barbell','https://i.imgur.com/y7z8a9b.gif','Lie on floor, press up.',''],
            [37,'Board Press','Chest','Pectorals','Barbell','https://i.imgur.com/c0d1e2f.gif','Lower to board on chest.',''],
            [38,'Slingshot Bench Press','Chest','Pectorals','Barbell','https://i.imgur.com/g3h4i5j.gif','Use slingshot for overload.',''],
            [39,'Dumbbell Bench Press','Chest','Pectorals','Dumbbell','https://i.imgur.com/k6l7m8n.gif','Press dumbbells up.',''],
            [40,'Incline Machine Press','Chest','Upper Chest','Machine','https://i.imgur.com/o9p0q1r.gif','Press on incline machine.',''],
            [41,'Decline Machine Press','Chest','Lower Chest','Machine','https://i.imgur.com/s2t3u4v.gif','Press on decline machine.',''],
            [42,'Pec Deck Fly','Chest','Pectorals','Machine','https://i.imgur.com/w5x6y7z.gif','Squeeze pads together.',''],
            [43,'Cable Chest Press','Chest','Pectorals','Cable','https://i.imgur.com/a8b9c0d.gif','Press cables forward.',''],
            [44,'Band Chest Fly','Chest','Pectorals','Band','https://i.imgur.com/e1f2g3h.gif','Pull band apart at chest.',''],
            [45,'Suspension Trainer Fly','Chest','Pectorals','TRX','https://i.imgur.com/i4j5k6l.gif','Lean forward, pull body up.',''],
            [46,'Medicine Ball Chest Pass','Chest','Pectorals','Medicine Ball','https://i.imgur.com/m7n8o9p.gif','Throw ball explosively.',''],
            [47,'Landmine Chest Press','Chest','Pectorals','Barbell','https://i.imgur.com/q0r1s2t.gif','Press barbell from shoulder.',''],
            [48,'Single-Arm Dumbbell Press','Chest','Pectorals','Dumbbell','https://i.imgur.com/u3v4w5x.gif','Press one dumbbell at a time.',''],
            [49,'Neutral-Grip Dumbbell Press','Chest','Pectorals','Dumbbell','https://i.imgur.com/y6z7a8b.gif','Palms face in.',''],
            [50,'Hex Press','Chest','Inner Chest','Dumbbell','https://i.imgur.com/c9d0e1f.gif','Press dumbbells together.'],
            // === 50 BACK EXERCISES (IDs 51–100) ===
            [51,'Pull-up','Back','Lats','Bodyweight','https://i.imgur.com/g2h3i4j.gif','Hang from bar, pull chin over bar.',''],
            [52,'Chin-up','Back','Lats','Bodyweight','https://i.imgur.com/k5l6m7n.gif','Palms face you, pull chin over bar.',''],
            [53,'Lat Pulldown (Wide)','Back','Lats','Cable','https://i.imgur.com/o8p9q0r.gif','Wide grip, pull bar to chest.',''],
            [54,'Bent-over Row (Barbell)','Back','Mid Back','Barbell','https://i.imgur.com/s1t2u3v.gif','Hinge at hips, pull bar to torso.',''],
            [55,'Seated Cable Row','Back','Mid Back','Cable','https://i.imgur.com/w4x5y6z.gif','Sit and pull handles to torso.',''],
            [56,'T-Bar Row','Back','Mid Back','Barbell','https://i.imgur.com/a7b8c9d.gif','Use V-handle, row bar to chest.',''],
            [57,'Deadlift (Conventional)','Back','Lower Back','Barbell','https://i.imgur.com/e0f1g2h.gif','Lift bar from ground to hips.',''],
            [58,'Single-Arm Dumbbell Row','Back','Lats','Dumbbell','https://i.imgur.com/i3j4k5l.gif','Knee on bench, row dumbbell up.',''],
            [59,'Face Pull','Back','Rear Delts','Cable','https://i.imgur.com/m6n7o8p.gif','Pull rope to face, elbows high.',''],
            [60,'Inverted Row','Back','Upper Back','Bodyweight','https://i.imgur.com/q9r0s1t.gif','Under bar, pull chest to bar.',''],
            [61,'Superman','Back','Lower Back','Bodyweight','https://i.imgur.com/u2v3w4x.gif','Lie face down, lift arms and legs.',''],
            [62,'Rack Pull','Back','Upper Back','Barbell','https://i.imgur.com/y5z6a7b.gif','Deadlift from knee height.',''],
            [63,'Pendlay Row','Back','Mid Back','Barbell','https://i.imgur.com/c8d9e0f.gif','Explosive row from floor.',''],
            [64,'Meadows Row','Back','Lats','Barbell','https://i.imgur.com/g1h2i3j.gif','Staggered stance, row with landmine.',''],
            [65,'Kroc Row','Back','Lats','Dumbbell','https://i.imgur.com/k4l5m6n.gif','High-rep, heavy single-arm row.',''],
            [66,'Straight-Arm Pulldown','Back','Lats','Cable','https://i.imgur.com/o7p8q9r.gif','Keep arms straight, pull bar down.',''],
            [67,'Neutral-Grip Pulldown','Back','Lats','Cable','https://i.imgur.com/s0t1u2v.gif','Parallel grip, pull to chest.',''],
            [68,'Reverse-Grip Row','Back','Lower Lats','Barbell','https://i.imgur.com/w3x4y5z.gif','Underhand grip, row bar.',''],
            [69,'Landmine Row','Back','Mid Back','Barbell','https://i.imgur.com/a6b7c8d.gif','Row barbell from landmine.',''],
            [70,'Chest-Supported Row','Back','Upper Back','Dumbbell','https://i.imgur.com/e9f0g1h.gif','Lie on incline, row dumbbells.',''],
            [71,'Band Pull-Apart','Back','Rear Delts','Band','https://i.imgur.com/i2j3k4l.gif','Pull band apart at chest level.',''],
            [72,'Hyperextension','Back','Lower Back','Bodyweight','https://i.imgur.com/m5n6o7p.gif','Hinge at hips, lift torso.',''],
            [73,'Bird Dog','Back','Core','Bodyweight','https://i.imgur.com/q8r9s0t.gif','Extend opposite arm and leg.',''],
            [74,'Yates Row','Back','Upper Back','Barbell','https://i.imgur.com/u1v2w3x.gif','45° torso, reverse grip row.',''],
            [75,'Seal Row','Back','Mid Back','Barbell','https://i.imgur.com/y4z5a6b.gif','Lie face down on bench, row bar.',''],
            [76,'Wide-Grip Seated Row','Back','Upper Back','Cable','https://i.imgur.com/c7d8e9f.gif','Wide grip, pull to chest.',''],
            [77,'Close-Grip Pulldown','Back','Lats','Cable','https://i.imgur.com/g0h1i2j.gif','V-bar, pull to chest.',''],
            [78,'Rope Pulldown','Back','Lats','Cable','https://i.imgur.com/k3l4m5n.gif','Pull rope apart at bottom.',''],
            [79,'Single-Arm Lat Pulldown','Back','Lats','Cable','https://i.imgur.com/o6p7q8r.gif','Unilateral pulldown.',''],
            [80,'Behind-the-Neck Pulldown','Back','Lats','Cable','https://i.imgur.com/s9t0u1v.gif','Pull bar behind head.',''],
            [81,'Weighted Pull-up','Back','Lats','Bodyweight','https://i.imgur.com/w2x3y4z.gif','Add weight via belt.',''],
            [82,'Neutral-Grip Pull-up','Back','Lats','Bodyweight','https://i.imgur.com/a5b6c7d.gif','Parallel bars, pull up.',''],
            [83,'Commando Pull-up','Back','Lats','Bodyweight','https://i.imgur.com/e8f9g0h.gif','Side-to-side pull-up.',''],
            [84,'Muscle-up','Back','Lats','Bodyweight','https://i.imgur.com/i1j2k3l.gif','Pull to dip transition.',''],
            [85,'Kipping Pull-up','Back','Lats','Bodyweight','https://i.imgur.com/m4n5o6p.gif','Use hip swing for momentum.',''],
            [86,'Towel Pull-up','Back','Grip','Towel','https://i.imgur.com/q7r8s9t.gif','Hang towel over bar, pull up.',''],
            [87,'Ring Row','Back','Upper Back','Rings','https://i.imgur.com/u0v1w2x.gif','Pull body to rings.',''],
            [88,'TRX Row','Back','Upper Back','TRX','https://i.imgur.com/y3z4a5b.gif','Pull body up using straps.',''],
            [89,'Dumbbell Rear Delt Row','Back','Rear Delts','Dumbbell','https://i.imgur.com/g9h0i1j.gif','Hinge, row to sides.',''],
            [90,'Cable Rear Delt Row','Back','Rear Delts','Cable','https://i.imgur.com/k2l3m4n.gif','Pull cable to face.',''],
            [91,'Snatch-Grip Deadlift','Back','Upper Back','Barbell','https://i.imgur.com/o5p6q7r.gif','Wide grip deadlift.',''],
            [92,'Trap Bar Deadlift','Back','Lower Back','Trap Bar','https://i.imgur.com/s8t9u0v.gif','Neutral grip, lift.',''],
            [93,'Block Pull','Back','Upper Back','Barbell','https://i.imgur.com/w1x2y3z.gif','Deadlift from blocks.',''],
            [94,'Deficit Deadlift','Back','Lower Back','Barbell','https://i.imgur.com/a4b5c6d.gif','Stand on plate, deadlift.',''],
            [95,'Sumo Deadlift','Back','Lower Back','Barbell','https://i.imgur.com/e7f8g9h.gif','Wide stance deadlift.',''],
            [96,'Romanian Deadlift','Back','Hamstrings','Barbell','https://i.imgur.com/i0j1k2l.gif','Hinge at hips.',''],
            [97,'Stiff-Leg Deadlift','Back','Hamstrings','Barbell','https://i.imgur.com/m3n4o5p.gif','Straight legs, hinge.',''],
            [98,'Good Morning','Back','Lower Back','Barbell','https://i.imgur.com/q6r7s8t.gif','Hinge forward with bar.',''],
            [99,'Reverse Hyperextension','Back','Lower Back','Machine','https://i.imgur.com/u9v0w1x.gif','Lift legs behind.',''],
            [100,'Glute-Ham Raise','Back','Hamstrings','Bodyweight','https://i.imgur.com/w2x3y4z.gif','Kneel, lower torso.'],
            // === 50 SHOULDERS (101–150) ===
            [101,'Overhead Press (Barbell)','Shoulders','Deltoids','Barbell','https://i.imgur.com/k2l3m4n.gif','Press bar from shoulders to overhead.',''],
            [102,'Dumbbell Shoulder Press','Shoulders','Deltoids','Dumbbell','https://i.imgur.com/o5p6q7r.gif','Press dumbbells from shoulders up.',''],
            [103,'Lateral Raise','Shoulders','Side Delts','Dumbbell','https://i.imgur.com/s8t9u0v.gif','Raise arms out to sides.',''],
            [104,'Front Raise','Shoulders','Front Delts','Dumbbell','https://i.imgur.com/w1x2y3z.gif','Raise arms straight in front.',''],
            [105,'Rear Delt Fly','Shoulders','Rear Delts','Dumbbell','https://i.imgur.com/a4b5c6d.gif','Hinge forward, raise arms out.',''],
            [106,'Arnold Press','Shoulders','Deltoids','Dumbbell','https://i.imgur.com/e7f8g9h.gif','Rotate palms while pressing up.',''],
            [107,'Upright Row','Shoulders','Traps','Barbell','https://i.imgur.com/i0j1k2l.gif','Pull bar to chin, elbows high.',''],
            [108,'Shrug (Dumbbell)','Shoulders','Traps','Dumbbell','https://i.imgur.com/m3n4o5p.gif','Lift shoulders to ears.',''],
            [109,'Cuban Press','Shoulders','Rotator Cuff','Dumbbell','https://i.imgur.com/q6r7s8t.gif','Upright row + external rotation + press.',''],
            [110,'Landmine Press','Shoulders','Deltoids','Barbell','https://i.imgur.com/u9v0w1x.gif','Press barbell from shoulder.',''],
            [111,'Behind-the-Neck Press','Shoulders','Deltoids','Barbell','https://i.imgur.com/w2x3y4z.gif','Press bar from behind head.',''],
            [112,'Plate Front Raise','Shoulders','Front Delts','Plate','https://i.imgur.com/a5b6c7d.gif','Hold plate, raise to eye level.',''],
            [113,'Cable Lateral Raise','Shoulders','Side Delts','Cable','https://i.imgur.com/e8f9g0h.gif','Raise arm out to side.',''],
            [114,'Y-Raise','Shoulders','Rear Delts','Dumbbell','https://i.imgur.com/i1j2k3l.gif','Raise arms in Y shape.',''],
            [115,'Handstand Push-up','Shoulders','Deltoids','Bodyweight','https://i.imgur.com/m4n5o6p.gif','Against wall, lower head to floor.',''],
            [116,'Face Pull (High)','Shoulders','Rear Delts','Cable','https://i.imgur.com/q7r8s9t.gif','Pull rope to forehead.',''],
            [117,'Cable Rear Delt Fly','Shoulders','Rear Delts','Cable','https://i.imgur.com/u0v1w2x.gif','Pull cables out to sides.',''],
            [118,'Barbell Shrug','Shoulders','Traps','Barbell','https://i.imgur.com/y3z4a5b.gif','Shrug shoulders with bar.',''],
            [119,'Farmer\'s Carry','Shoulders','Traps','Dumbbell','https://i.imgur.com/c6d7e8f.gif','Walk with heavy weights.',''],
            [120,'Z Press','Shoulders','Deltoids','Barbell','https://i.imgur.com/g9h0i1j.gif','Sit on floor, press bar up.',''],
            [121,'Viking Press','Shoulders','Deltoids','Machine','https://i.imgur.com/k2l3m4n.gif','Press handles up.',''],
            [122,'Push Press','Shoulders','Deltoids','Barbell','https://i.imgur.com/o5p6q7r.gif','Use leg drive to press.',''],
            [123,'Jerk Press','Shoulders','Deltoids','Barbell','https://i.imgur.com/s8t9u0v.gif','Split or power jerk.',''],
            [124,'Single-Arm Landmine Press','Shoulders','Deltoids','Barbell','https://i.imgur.com/w1x2y3z.gif','Press one side.',''],
            [125,'Kettlebell Press','Shoulders','Deltoids','Kettlebell','https://i.imgur.com/a4b5c6d.gif','Press kettlebell overhead.',''],
            [126,'Double Kettlebell Press','Shoulders','Deltoids','Kettlebell','https://i.imgur.com/e7f8g9h.gif','Press two bells.',''],
            [127,'Bottoms-Up Press','Shoulders','Deltoids','Kettlebell','https://i.imgur.com/i0j1k2l.gif','Hold bell upside down.',''],
            [128,'Seated Dumbbell Press','Shoulders','Deltoids','Dumbbell','https://i.imgur.com/m3n4o5p.gif','Press while seated.',''],
            [129,'Neutral-Grip Press','Shoulders','Deltoids','Dumbbell','https://i.imgur.com/q6r7s8t.gif','Palms face in.',''],
            [130,'Incline Lateral Raise','Shoulders','Side Delts','Dumbbell','https://i.imgur.com/u9v0w1x.gif','Lie on incline, raise arms.',''],
            [131,'Cable Front Raise','Shoulders','Front Delts','Cable','https://i.imgur.com/w2x3y4z.gif','Raise cable in front.',''],
            [132,'Band Lateral Raise','Shoulders','Side Delts','Band','https://i.imgur.com/a5b6c7d.gif','Step on band, raise arms.',''],
            [133,'Trap Bar Overhead Press','Shoulders','Deltoids','Trap Bar','https://i.imgur.com/e8f9g0h.gif','Press trap bar.',''],
            [134,'Log Press','Shoulders','Deltoids','Log','https://i.imgur.com/i1j2k3l.gif','Press log overhead.',''],
            [135,'Axle Press','Shoulders','Deltoids','Axle','https://i.imgur.com/m4n5o6p.gif','Press thick bar.',''],
            [136,'Pike Press','Shoulders','Deltoids','Bodyweight','https://i.imgur.com/k2l3m4n.gif','Pike position, press head down.',''],
            [137,'Wall Walk','Shoulders','Deltoids','Bodyweight','https://i.imgur.com/o5p6q7r.gif','Walk up wall to handstand.',''],
            [138,'Shoulder Tap','Shoulders','Deltoids','Bodyweight','https://i.imgur.com/s8t9u0v.gif','Tap shoulder in plank.',''],
            [139,'Deficit Handstand Push-up','Shoulders','Deltoids','Bodyweight','https://i.imgur.com/w1x2y3z.gif','Hands on blocks.',''],
            [140,'90-Degree Push-up','Shoulders','Deltoids','Bodyweight','https://i.imgur.com/a4b5c6d.gif','Elbows at 90°.',''],
            [141,'TRX Y-Raise','Shoulders','Rear Delts','TRX','https://i.imgur.com/m3n4o5p.gif','Pull body up in Y.',''],
            [142,'TRX Face Pull','Shoulders','Rear Delts','TRX','https://i.imgur.com/q6r7s8t.gif','Pull straps to face.',''],
            [143,'Band Pull-Apart','Shoulders','Rear Delts','Band','https://i.imgur.com/u9v0w1x.gif','Pull band apart.',''],
            [144,'External Rotation','Shoulders','Rotator Cuff','Dumbbell','https://i.imgur.com/a5b6c7d.gif','Rotate arm outward.',''],
            [145,'Internal Rotation','Shoulders','Rotator Cuff','Cable','https://i.imgur.com/e8f9g0h.gif','Rotate arm inward.',''],
            [146,'Sword Pull','Shoulders','Rear Delts','Cable','https://i.imgur.com/m4n5o6p.gif','Pull cable across body.',''],
            [147,'Rear Delt Row','Shoulders','Rear Delts','Cable','https://i.imgur.com/q7r8s9t.gif','Row with elbows high.',''],
            [148,'W-Raise','Shoulders','Rear Delts','Dumbbell','https://i.imgur.com/u0v1w2x.gif','Raise arms in W shape.',''],
            [149,'Scapular Wall Slide','Shoulders','Scapula','Bodyweight','https://i.imgur.com/y3z4a5b.gif','Slide arms up wall.',''],
            [150,'Scapular Push-up','Shoulders','Serratus','Bodyweight','https://i.imgur.com/c6d7e8f.gif','Protract scapula in plank.'],
            // === 50 ARMS (151–200) ===
            [151,'Bicep Curl (Dumbbell)','Arms','Biceps','Dumbbell','https://i.imgur.com/k2l3m4n.gif','Curl weights to shoulders.',''],
            [152,'Hammer Curl','Arms','Biceps','Dumbbell','https://i.imgur.com/o5p6q7r.gif','Curl with palms facing in.',''],
            [153,'Concentration Curl','Arms','Biceps','Dumbbell','https://i.imgur.com/s8t9u0v.gif','Sit, curl one arm, elbow on thigh.',''],
            [154,'Cable Curl','Arms','Biceps','Cable','https://i.imgur.com/w1x2y3z.gif','Pull rope/bar toward chest.',''],
            [155,'Preacher Curl','Arms','Biceps','EZ Bar','https://i.imgur.com/a4b5c6d.gif','Arms on pad, curl bar.',''],
            [156,'Tricep Dip','Arms','Triceps','Bodyweight','https://i.imgur.com/e7f8g9h.gif','Lower body using arms on bench.',''],
            [157,'Tricep Pushdown','Arms','Triceps','Cable','https://i.imgur.com/i0j1k2l.gif','Push rope down, elbows fixed.',''],
            [158,'Skull Crusher','Arms','Triceps','EZ Bar','https://i.imgur.com/m3n4o5p.gif','Lower bar to forehead, extend arms.',''],
            [159,'Overhead Tricep Extension','Arms','Triceps','Dumbbell','https://i.imgur.com/q6r7s8t.gif','Hold weight overhead, lower behind head.',''],
            [160,'Close-Grip Bench Press','Arms','Triceps','Barbell','https://i.imgur.com/u9v0w1x.gif','Hands shoulder-width, lower to chest.',''],
            [161,'Rope Pushdown','Arms','Triceps','Cable','https://i.imgur.com/w2x3y4z.gif','Pull rope apart at bottom.',''],
            [162,'21s Bicep Curl','Arms','Biceps','Dumbbell','https://i.imgur.com/a5b6c7d.gif','7 half bottom, 7 half top, 7 full.',''],
            [163,'Zottman Curl','Arms','Biceps','Dumbbell','https://i.imgur.com/e8f9g0h.gif','Curl up, rotate, lower slow.',''],
            [164,'Spider Curl','Arms','Biceps','Dumbbell','https://i.imgur.com/i1j2k3l.gif','Face down on incline, curl.',''],
            [165,'Kickback','Arms','Triceps','Dumbbell','https://i.imgur.com/m4n5o6p.gif','Hinge forward, extend arm back.',''],
            [166,'Reverse Curl','Arms','Forearms','Barbell','https://i.imgur.com/q7r8s9t.gif','Palms down, curl bar.',''],
            [167,'Wrist Curl','Arms','Forearms','Dumbbell','https://i.imgur.com/u0v1w2x.gif','Curl wrists up with palms up.',''],
            [168,'Reverse Wrist Curl','Arms','Forearms','Dumbbell','https://i.imgur.com/y3z4a5b.gif','Curl wrists up with palms down.',''],
            [169,'Pinch Grip Plate Hold','Arms','Forearms','Plate','https://i.imgur.com/c6d7e8f.gif','Pinch plate between fingers.',''],
            [170,'Towel Pull-up','Arms','Grip','Towel','https://i.imgur.com/g9h0i1j.gif','Hang towel over bar, pull up.',''],
            [171,'Cable Hammer Curl','Arms','Biceps','Cable','https://i.imgur.com/k2l3m4n.gif','Rope attachment, curl with neutral grip.',''],
            [172,'Incline Dumbbell Curl','Arms','Biceps','Dumbbell','https://i.imgur.com/o5p6q7r.gif','Lie on incline, curl dumbbells.',''],
            [173,'Bayesian Cable Curl','Arms','Biceps','Cable','https://i.imgur.com/s8t9u0v.gif','Behind back, curl cable.',''],
            [174,'JM Press','Arms','Triceps','Barbell','https://i.imgur.com/w1x2y3z.gif','Hybrid skull crusher + close-grip press.',''],
            [175,'Diamond Dip','Arms','Triceps','Bodyweight','https://i.imgur.com/a4b5c6d.gif','Hands form diamond on dip bar.',''],
            [176,'Ring Dip','Arms','Triceps','Rings','https://i.imgur.com/e7f8g9h.gif','Dip on rings.',''],
            [177,'Bench Dip','Arms','Triceps','Bodyweight','https://i.imgur.com/i0j1k2l.gif','Feet on bench, dip.',''],
            [178,'Weighted Dip','Arms','Triceps','Bodyweight','https://i.imgur.com/m3n4o5p.gif','Add weight via belt.',''],
            [179,'Machine Dip','Arms','Triceps','Machine','https://i.imgur.com/q6r7s8t.gif','Dip on machine.',''],
            [180,'V-Bar Pushdown','Arms','Triceps','Cable','https://i.imgur.com/u9v0w1x.gif','Push V-bar down.',''],
            [181,'Single-Arm Pushdown','Arms','Triceps','Cable','https://i.imgur.com/w2x3y4z.gif','Unilateral pushdown.',''],
            [182,'Reverse-Grip Pushdown','Arms','Triceps','Cable','https://i.imgur.com/a5b6c7d.gif','Palms up, push down.',''],
            [183,'Overhead Rope Extension','Arms','Triceps','Cable','https://i.imgur.com/e8f9g0h.gif','Pull rope overhead.',''],
            [184,'Cable Kickback','Arms','Triceps','Cable','https://i.imgur.com/i1j2k3l.gif','Extend arm back.',''],
            [185,'Tate Press','Arms','Triceps','Dumbbell','https://i.imgur.com/m4n5o6p.gif','Lower dumbbells to chest.',''],
            [186,'Rolling Tricep Extension','Arms','Triceps','Dumbbell','https://i.imgur.com/q7r8s9t.gif','Roll then extend.',''],
            [187,'EZ Bar Curl','Arms','Biceps','EZ Bar','https://i.imgur.com/u0v1w2x.gif','Curl EZ bar.',''],
            [188,'Close-Grip Curl','Arms','Biceps','EZ Bar','https://i.imgur.com/y3z4a5b.gif','Narrow grip curl.',''],
            [189,'Wide-Grip Curl','Arms','Biceps','EZ Bar','https://i.imgur.com/c6d7e8f.gif','Wide grip curl.',''],
            [190,'Drag Curl','Arms','Biceps','Barbell','https://i.imgur.com/g9h0i1j.gif','Drag bar up body.',''],
            [191,'Chin-up','Arms','Biceps','Bodyweight','https://i.imgur.com/k2l3m4n.gif','Palms face you.',''],
            [192,'Neutral-Grip Pull-up','Arms','Biceps','Bodyweight','https://i.imgur.com/o5p6q7r.gif','Parallel grip.',''],
            [193,'Rope Climb','Arms','Biceps','Rope','https://i.imgur.com/s8t9u0v.gif','Climb rope.',''],
            [194,'Fat Bar Curl','Arms','Biceps','Fat Bar','https://i.imgur.com/w1x2y3z.gif','Thick bar curl.',''],
            [195,'Kettlebell Curl','Arms','Biceps','Kettlebell','https://i.imgur.com/a4b5c6d.gif','Curl kettlebell.',''],
            [196,'Band Curl','Arms','Biceps','Band','https://i.imgur.com/e7f8g9h.gif','Step on band, curl.',''],
            [197,'Isometric Curl','Arms','Biceps','Barbell','https://i.imgur.com/i0j1k2l.gif','Hold at 90°.',''],
            [198,'Eccentric Curl','Arms','Biceps','Dumbbell','https://i.imgur.com/m3n4o5p.gif','Lower slowly.',''],
            [199,'Cross-Body Hammer Curl','Arms','Biceps','Dumbbell','https://i.imgur.com/q6r7s8t.gif','Curl across body.',''],
            [200,'Waiter Curl','Arms','Biceps','Plate','https://i.imgur.com/u9v0w1x.gif','Hold plate like waiter.'],
            // === 50 LEGS (201–250) ===
            [201,'Squat (Barbell)','Legs','Quads','Barbell','https://i.imgur.com/k2l3m4n.gif','Lower hips below knees, stand up.',''],
            [202,'Front Squat','Legs','Quads','Barbell','https://i.imgur.com/o5p6q7r.gif','Bar on front shoulders, squat.',''],
            [203,'Goblet Squat','Legs','Quads','Dumbbell','https://i.imgur.com/s8t9u0v.gif','Hold weight at chest, squat.',''],
            [204,'Bulgarian Split Squat','Legs','Quads','Dumbbell','https://i.imgur.com/w1x2y3z.gif','Rear foot elevated, lower front knee.',''],
            [205,'Lunges (Walking)','Legs','Quads','Bodyweight','https://i.imgur.com/a4b5c6d.gif','Step forward, lower back knee.',''],
            [206,'Leg Press','Legs','Quads','Machine','https://i.imgur.com/e7f8g9h.gif','Push platform away with feet.',''],
            [207,'Leg Extension','Legs','Quads','Machine','https://i.imgur.com/i0j1k2l.gif','Extend legs against pad.',''],
            [208,'Romanian Deadlift','Legs','Hamstrings','Barbell','https://i.imgur.com/m3n4o5p.gif','Hinge at hips, lower bar.',''],
            [209,'Hamstring Curl (Lying)','Legs','Hamstrings','Machine','https://i.imgur.com/q6r7s8t.gif','Curl heels toward glutes.',''],
            [210,'Good Morning','Legs','Hamstrings','Barbell','https://i.imgur.com/u9v0w1x.gif','Hinge forward with bar on back.',''],
            [211,'Glute Bridge','Legs','Glutes','Bodyweight','https://i.imgur.com/w2x3y4z.gif','Lift hips off ground.',''],
            [212,'Hip Thrust','Legs','Glutes','Barbell','https://i.imgur.com/a5b6c7d.gif','Thrust hips up with bar.',''],
            [213,'Step-up','Legs','Quads','Box','https://i.imgur.com/e8f9g0h.gif','Step onto box, drive up.',''],
            [214,'Calf Raise (Standing)','Legs','Calves','Bodyweight','https://i.imgur.com/i1j2k3l.gif','Rise onto toes.',''],
            [215,'Seated Calf Raise','Legs','Calves','Machine','https://i.imgur.com/m4n5o6p.gif','Lift heels while seated.',''],
            [216,'Box Jump','Legs','Quads','Box','https://i.imgur.com/q7r8s9t.gif','Jump onto box, stand tall.',''],
            [217,'Pistol Squat','Legs','Quads','Bodyweight','https://i.imgur.com/u0v1w2x.gif','Single-leg squat to full depth.',''],
            [218,'Sumo Deadlift','Legs','Inner Thighs','Barbell','https://i.imgur.com/y3z4a5b.gif','Wide stance, pull bar up.',''],
            [219,'Farmer\'s Walk','Legs','Grip','Dumbbell','https://i.imgur.com/c6d7e8f.gif','Walk with heavy weights.',''],
            [220,'Sissy Squat','Legs','Quads','Bodyweight','https://i.imgur.com/g9h0i1j.gif','Lean back, lower knees to ground.',''],
            [221,'Hack Squat','Legs','Quads','Machine','https://i.imgur.com/k2l3m4n.gif','Push platform up with shoulders.',''],
            [222,'Jefferson Squat','Legs','Quads','Barbell','https://i.imgur.com/o5p6q7r.gif','Straddle bar, squat down.',''],
            [223,'Zercher Squat','Legs','Quads','Barbell','https://i.imgur.com/s8t9u0v.gif','Hold bar in elbow crooks.',''],
            [224,'Landmine Squat','Legs','Quads','Barbell','https://i.imgur.com/w1x2y3z.gif','Hold barbell end, squat.',''],
            [225,'Reverse Lunge','Legs','Quads','Bodyweight','https://i.imgur.com/a4b5c6d.gif','Step back, lower knee.',''],
            [226,'Curtsy Lunge','Legs','Glutes','Bodyweight','https://i.imgur.com/e7f8g9h.gif','Cross leg behind, lower.',''],
            [227,'Single-Leg RDL','Legs','Hamstrings','Dumbbell','https://i.imgur.com/i0j1k2l.gif','Hinge on one leg.',''],
            [228,'Nordic Curl','Legs','Hamstrings','Bodyweight','https://i.imgur.com/m3n4o5p.gif','Kneel, lower torso slowly.',''],
            [229,'Glute Kickback','Legs','Glutes','Cable','https://i.imgur.com/q6r7s8t.gif','Kick leg back against cable.',''],
            [230,'Donkey Calf Raise','Legs','Calves','Machine','https://i.imgur.com/u9v0w1x.gif','Lean forward, raise heels.',''],
            [231,'Single-Leg Calf Raise','Legs','Calves','Bodyweight','https://i.imgur.com/w2x3y4z.gif','Raise on one leg.',''],
            [232,'Jump Squat','Legs','Quads','Bodyweight','https://i.imgur.com/a5b6c7d.gif','Squat and explode up.',''],
            [233,'Wall Sit','Legs','Quads','Bodyweight','https://i.imgur.com/e8f9g0h.gif','Hold squat against wall.',''],
            [234,'Leg Press (Single-Leg)','Legs','Quads','Machine','https://i.imgur.com/i1j2k3l.gif','Press with one leg.',''],
            [235,'Glute-Ham Raise','Legs','Hamstrings','Bodyweight','https://i.imgur.com/m4n5o6p.gif','Lower torso from knees.',''],
            [236,'Seated Leg Curl','Legs','Hamstrings','Machine','https://i.imgur.com/q7r8s9t.gif','Curl while seated.',''],
            [237,'Hip Abduction','Legs','Abductors','Machine','https://i.imgur.com/u0v1w2x.gif','Push legs out.',''],
            [238,'Hip Adduction','Legs','Adductors','Machine','https://i.imgur.com/y3z4a5b.gif','Squeeze legs in.',''],
            [239,'Calf Press on Leg Press','Legs','Calves','Machine','https://i.imgur.com/c6d7e8f.gif','Press with toes.',''],
            [240,'Smith Machine Squat','Legs','Quads','Machine','https://i.imgur.com/g9h0i1j.gif','Squat in Smith rack.',''],
            [241,'Safety Bar Squat','Legs','Quads','Barbell','https://i.imgur.com/k2l3m4n.gif','Use safety bar.',''],
            [242,'Belt Squat','Legs','Quads','Machine','https://i.imgur.com/o5p6q7r.gif','Squat with belt load.',''],
            [243,'Pause Squat','Legs','Quads','Barbell','https://i.imgur.com/s8t9u0v.gif','Pause at bottom.',''],
            [244,'Anderson Squat','Legs','Quads','Barbell','https://i.imgur.com/w1x2y3z.gif','Start from pins.',''],
            [245,'1.5 Rep Squat','Legs','Quads','Barbell','https://i.imgur.com/a4b5c6d.gif','Full + half rep.',''],
            [246,'Tempo Squat','Legs','Quads','Barbell','https://i.imgur.com/e7f8g9h.gif','3-1-3-1 tempo.',''],
            [247,'Box Squat','Legs','Quads','Barbell','https://i.imgur.com/i0j1k2l.gif','Sit back to box.',''],
            [248,'Zercher Carry','Legs','Quads','Barbell','https://i.imgur.com/m3n4o5p.gif','Walk with bar in elbows.',''],
            [249,'Sled Push','Legs','Quads','Sled','https://i.imgur.com/q6r7s8t.gif','Push sled forward.',''],
            [250,'Sled Pull','Legs','Hamstrings','Sled','https://i.imgur.com/u9v0w1x.gif','Pull sled backward.'],
            // === 50 CORE (251–300) ===
            [251,'Plank','Core','Abs','Bodyweight','https://i.imgur.com/w2x3y4z.gif','Hold forearm plank, core tight.',''],
            [252,'Side Plank','Core','Obliques','Bodyweight','https://i.imgur.com/a5b6c7d.gif','Hold on one forearm, body straight.',''],
            [253,'Russian Twist','Core','Obliques','Bodyweight','https://i.imgur.com/e8f9g0h.gif','Rotate torso side to side.',''],
            [254,'Hanging Leg Raise','Core','Lower Abs','Bodyweight','https://i.imgur.com/i1j2k3l.gif','Hang, lift legs to 90°.',''],
            [255,'Bicycle Crunch','Core','Abs','Bodyweight','https://i.imgur.com/m4n5o6p.gif','Alternate knee to opposite elbow.',''],
            [256,'Mountain Climber','Core','Abs','Bodyweight','https://i.imgur.com/q7r8s9t.gif','Run knees to chest in plank.',''],
            [257,'Ab Wheel Rollout','Core','Abs','Ab Wheel','https://i.imgur.com/u0v1w2x.gif','Roll wheel forward, extend body.',''],
            [258,'V-up','Core','Abs','Bodyweight','https://i.imgur.com/y3z4a5b.gif','Lift torso and legs to form V.',''],
            [259,'Flutter Kick','Core','Lower Abs','Bodyweight','https://i.imgur.com/c6d7e8f.gif','Lie on back, scissor legs.',''],
            [260,'Dead Bug','Core','Abs','Bodyweight','https://i.imgur.com/g9h0i1j.gif','Extend opposite arm and leg.',''],
            [261,'Woodchopper','Core','Obliques','Cable','https://i.imgur.com/k2l3m4n.gif','Pull cable from high to low across body.',''],
            [262,'Cable Crunch','Core','Abs','Cable','https://i.imgur.com/o5p6q7r.gif','Kneel, pull rope down while crunching.',''],
            [263,'Dragon Flag','Core','Abs','Bodyweight','https://i.imgur.com/s8t9u0v.gif','Lie on bench, lift body straight.',''],
            [264,'Windshield Wiper','Core','Obliques','Bodyweight','https://i.imgur.com/w1x2y3z.gif','Legs up, rotate side to side.',''],
            [265,'Hollow Hold','Core','Abs','Bodyweight','https://i.imgur.com/a4b5c6d.gif','Lie on back, lift shoulders and legs.',''],
            [266,'Bear Crawl','Core','Abs','Bodyweight','https://i.imgur.com/e7f8g9h.gif','Crawl on all fours, core tight.',''],
            [267,'L-Sit','Core','Abs','Bodyweight','https://i.imgur.com/i0j1k2l.gif','Lift body with arms, legs straight.',''],
            [268,'Toes to Bar','Core','Abs','Bodyweight','https://i.imgur.com/m3n4o5p.gif','Hang, lift toes to bar.',''],
            [269,'Jackknife','Core','Abs','Bodyweight','https://i.imgur.com/q6r7s8t.gif','Pull knees to chest while lifting torso.',''],
            [270,'Sit-up','Core','Abs','Bodyweight','https://i.imgur.com/u9v0w1x.gif','Lie on back, sit all the way up.',''],
            [271,'Crunches','Core','Upper Abs','Bodyweight','https://i.imgur.com/w2x3y4z.gif','Lift shoulders off ground.',''],
            [272,'Reverse Crunch','Core','Lower Abs','Bodyweight','https://i.imgur.com/a5b6c7d.gif','Lift hips off ground.',''],
            [273,'Heel Taps','Core','Obliques','Bodyweight','https://i.imgur.com/e8f9g0h.gif','Tap heels side to side.',''],
            [274,'Plank Hip Dips','Core','Obliques','Bodyweight','https://i.imgur.com/i1j2k3l.gif','Rotate hips side to side in plank.',''],
            [275,'Scissor Kicks','Core','Lower Abs','Bodyweight','https://i.imgur.com/m4n5o6p.gif','Cross legs in air.',''],
            [276,'Hanging Knee Raise','Core','Lower Abs','Bodyweight','https://i.imgur.com/q7r8s9t.gif','Hang, lift knees to chest.',''],
            [277,'Medicine Ball Slam','Core','Abs','Medicine Ball','https://i.imgur.com/u0v1w2x.gif','Slam ball to ground.',''],
            [278,'Turkish Get-up','Core','Full Body','Kettlebell','https://i.imgur.com/y3z4a5b.gif','Lie to stand with weight overhead.',''],
            [279,'Landmine Twist','Core','Obliques','Barbell','https://i.imgur.com/c6d7e8f.gif','Rotate bar side to side.',''],
            [280,'Pallof Press','Core','Anti-Rotation','Cable','https://i.imgur.com/g9h0i1j.gif','Press cable away, resist rotation.',''],
            [281,'Side Bend','Core','Obliques','Dumbbell','https://i.imgur.com/k2l3m4n.gif','Bend to side with weight.',''],
            [282,'Farmer\'s Carry','Core','Abs','Dumbbell','https://i.imgur.com/o5p6q7r.gif','Walk with heavy weights.',''],
            [283,'Suitcase Carry','Core','Obliques','Dumbbell','https://i.imgur.com/s8t9u0v.gif','Carry one weight, resist tilt.',''],
            [284,'Overhead Carry','Core','Abs','Plate','https://i.imgur.com/w1x2y3z.gif','Walk with plate overhead.',''],
            [285,'Plank Row','Core','Abs','Dumbbell','https://i.imgur.com/a4b5c6d.gif','Row in plank position.',''],
            [286,'Bird Dog','Core','Abs','Bodyweight','https://i.imgur.com/e7f8g9h.gif','Extend opposite arm and leg.',''],
            [287,'Dead Bug (Weighted)','Core','Abs','Dumbbell','https://i.imgur.com/i0j1k2l.gif','Hold weights, extend limbs.',''],
            [288,'Hollow Rock','Core','Abs','Bodyweight','https://i.imgur.com/m3n4o5p.gif','Rock in hollow position.',''],
            [289,'Stir the Pot','Core','Abs','Stability Ball','https://i.imgur.com/q6r7s8t.gif','Circle elbows on ball.',''],
            [290,'Plank with Shoulder Tap','Core','Abs','Bodyweight','https://i.imgur.com/u9v0w1x.gif','Tap opposite shoulder.',''],
            [291,'Side Plank with Hip Lift','Core','Obliques','Bodyweight','https://i.imgur.com/w2x3y4z.gif','Lift and lower hips.',''],
            [292,'Ab Wheel Kneeling','Core','Abs','Ab Wheel','https://i.imgur.com/a5b6c7d.gif','Roll from knees.',''],
            [293,'Hanging Windshield Wiper','Core','Obliques','Bodyweight','https://i.imgur.com/e8f9g0h.gif','Rotate legs side to side while hanging.',''],
            [294,'Captain\'s Chair Leg Raise','Core','Lower Abs','Machine','https://i.imgur.com/i1j2k3l.gif','Lift legs in chair.',''],
            [295,'Decline Sit-up','Core','Abs','Bodyweight','https://i.imgur.com/m4n5o6p.gif','Sit up on decline bench.',''],
            [296,'Cable Woodchopper (Low to High)','Core','Obliques','Cable','https://i.imgur.com/q7r8s9t.gif','Pull from low to high.',''],
            [297,'Cable Woodchopper (High to Low)','Core','Obliques','Cable','https://i.imgur.com/u0v1w2x.gif','Pull from high to low.',''],
            [298,'Russian Twist (Weighted)','Core','Obliques','Medicine Ball','https://i.imgur.com/y3z4a5b.gif','Twist with ball.',''],
            [299,'Plank with Knee Drive','Core','Abs','Bodyweight','https://i.imgur.com/c6d7e8f.gif','Drive knee to elbow.',''],
            [300,'Pallof Press (Rotational)','Core','Anti-Rotation','Cable','https://i.imgur.com/g9h0i1j.gif','Press and rotate slightly.']
        ];

        foreach ($exercises as $ex) {
            $stmt->execute($ex);
        }
    }
    // Optional: Insert a default test user
    $pdo->prepare("
        INSERT IGNORE INTO users (id, username, email, password_hash)
        VALUES (1, 'testuser', 'test@rawfit.com', '\$2y\$10\$examplehash')
    ")->execute();
} catch (PDOException $e) {
    die("DB error: " . htmlspecialchars($e->getMessage()));
}
?>